version: "3.9"
services:
  postgres:
    container_name: postgresDB3
    image: postgres:16.1
    restart: always
    environment:
      POSTGRES_DB: commentsDB
      POSTGRES_USER: root
      POSTGRES_PASSWORD: pass
    ports:
      - "5435:5432"
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    command: redis-server --requirepass pass
    volumes:
      - redis-data:/data
    restart: unless-stopped

volumes:
  redis-data: